#version: '3.8'
#
#services:
#  linkedin-email-extractor:
#    build: .
#    ports:
#      - "5000:5000"
#    volumes:
#      - .:/app
#    environment:
#      - FLASK_ENV=development
#    restart: unless-stopped


